spring.application.name=management-student-java-spring

spring.jpa.hibernate.ddl-auto=none
server.port=8080
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=StudentCourseManagement;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
# color terminal
spring.output.ansi.enabled=ALWAYS
#start page = 1
spring.data.web.pageable.one-indexed-parameters=true

# use git bash here
#config jwt
# openssl rand -base64 64
djnd.jwt.base64-secret=nE6Od1T/x2GDldpDXhd9uaXfQupvYU7fCgO4IXPG3B2on76ZvM9hmGT7CR4sOPZmVu8R7u4+Uwy9Zik+fOwq9A==
djnd.jwt.access-token-validity-in-seconds=604800
djnd.jwt.refresh-token-validity-in-seconds=1296000
